POST http://localhost:5000/user-api/register-user
Content-Type:application/json

{
    "name":"varun sandesh",
    "password":"varun@123",
    "email":"varunravula9949@gmail.com",
    "mobile":"8985711858"
}

###
GET http://localhost:5000/user-api/get-users

###
POST http://localhost:5000/user-api/login-user
Content-Type:application/json

{
    "email":"varun@gmail.com",
    "password":"varun@123"
}

###
GET http://localhost:5000/user-api/get-users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InZhcnVucmF2dWxhOTk0OUBnbWFpbC5jb20iLCJpYXQiOjE3NDM5OTcxMDEsImV4cCI6MTc0Mzk5NzEzMX0.DD5oBwtNrn6DZKZRdIxzRCLpEbM9uzGW1FLfPNRpAFk

###
GET http://localhost:5000/user-api/get-user/varunravula9949@gmail.com
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InZhcnVucmF2dWxhOTk0OUBnbWFpbC5jb20iLCJpYXQiOjE3NDM5OTM1NDMsImV4cCI6MTc0Mzk5MzU3M30.Lb2n1A7tkFmZKycR-9hjI6-iqp_KbokWpoBH8tAoG_Q

###
GET http://localhost:5000/products-api/get-products
